name: Fetch and Filter News

on:
  schedule:
    - cron: '0 3 * * *'  # JSTで12:00
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python main.py

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add filtered_news.json
          git commit -m "Update news" || echo "No changes"
          git push

      - name: Commit and push filtered news and log
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add filtered_news.json filter_log.txt
          git commit -m "Update filtered news and log"
          git push
